"""Удален столбец в Users

Revision ID: 7ad9a4f1db69
Revises: a50609336fa4
Create Date: 2025-02-16 12:26:13.361498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad9a4f1db69'
down_revision: Union[str, None] = 'a50609336fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ot4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ot4', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
