"""Новый столбец в Users

Revision ID: a50609336fa4
Revises: 9b3f9c76fbd9
Create Date: 2025-02-16 12:25:40.110341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50609336fa4'
down_revision: Union[str, None] = '9b3f9c76fbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ot4', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ot4')
    # ### end Alembic commands ###
